'use client';

import React, { useState, use } from 'react';
import { ArrowLeft, CheckCircle2, Loader2, Calendar, MapPin, AlertCircle, UploadCloud, Smartphone } from 'lucide-react';

// Custom lightweight markdown parser for public view
const MarkdownPreview = ({ text, className = "" }: { text?: string, className?: string }) => {
  if (!text) return null;
  
  let html = text
    .replace(/</g, '&lt;').replace(/>/g, '&gt;') // Basic sanitize
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold
    .replace(/\[(.*?)\]\((.*?)\)/g, '<a href="$2" class="text-[#A65D24] hover:underline" target="_blank">$1</a>') // Links
    .replace(/!!(.*?)!!/g, '<span class="text-red-500 font-medium">$1</span>'); // Red Text

  const lines = html.split('\n');
  let inUl = false, inOl = false, result = '';

  lines.forEach(line => {
    if (line.trim().startsWith('- ')) {
      if (!inUl) { result += '<ul class="list-disc pl-5 my-1 space-y-1">'; inUl = true; }
      result += `<li>${line.substring(2)}</li>`;
    } else if (/^\d+\.\s/.test(line.trim())) {
      if (!inOl) { result += '<ol class="list-decimal pl-5 my-1 space-y-1">'; inOl = true; }
      result += `<li>${line.replace(/^\d+\.\s/, '')}</li>`;
    } else {
      if (inUl) { result += '</ul>'; inUl = false; }
      if (inOl) { result += '</ol>'; inOl = false; }
      result += `${line}<br />`;
    }
  });
  if (inUl) result += '</ul>';
  if (inOl) result += '</ol>';

  return <div dangerouslySetInnerHTML={{ __html: result }} className={`text-sm text-stone-500 mt-1.5 ${className}`} />;
};

// MOCK DATA: Updated to exactly match the schema structure generated by our Form Builder
const mockFormData = {
  id: 'f_1',
  event_id: 'evt_1',
  titleEn: '7-Day Silent Zen Retreat - Application',
  titleZh: '七日內觀止語禪修營 - 報名表單',
  subtitleEn: 'Please read the [Retreat Guidelines](https://daoji.org/guidelines) before applying.',
  subtitleZh: '報名前請先閱讀[禪修營須知](https://daoji.org/guidelines)。',
  schedule_display: {
    en: 'October 1st - October 7th, 2026',
    zh: '2026年10月1日 - 10月7日'
  },
  location: {
    en: 'Maggapaṭipadā Main Hall, Lantau',
    zh: '道跡禪院 主禪堂 (大嶼山)'
  },
  formStatus: 'open',
  schema: [
    {
      id: 'field_1',
      dataKey: 'full_name',
      type: 'text',
      labelEn: 'Full Legal Name',
      labelZh: '真實姓名',
      descriptionEn: 'Please enter your name exactly as it appears on your ID card.\n!!Do not use nicknames.!!',
      descriptionZh: '請輸入與您的身份證上完全相同的姓名。\n!!請勿使用暱稱。!!',
      required: true,
    },
    {
      id: 'field_2',
      dataKey: 'mobile_number',
      type: 'mobile',
      labelEn: 'Mobile Number',
      labelZh: '手機號碼',
      required: true,
    },
    {
      id: 'field_3',
      dataKey: 'dietary_requirements',
      type: 'select',
      labelEn: 'Dietary Requirements',
      labelZh: '飲食要求',
      required: true,
      options: [
        { value: 'regular', labelEn: 'None / Regular', labelZh: '無 / 普通飲食' },
        { value: 'vegetarian', labelEn: 'Vegetarian', labelZh: '素食' },
        { value: 'other', labelEn: 'Other', labelZh: '其他' }
      ]
    },
    {
      id: 'field_4',
      dataKey: 'dietary_other',
      type: 'text',
      labelEn: 'Please specify your diet',
      labelZh: '請具體說明您的飲食',
      required: true,
      condition: { 
        match: 'AND', 
        rules: [{ id: 'rule_1', dependsOn: 'dietary_requirements', operator: 'equals', value: 'other' }] 
      }
    },
    {
      id: 'field_5',
      dataKey: 'attendance_days',
      type: 'checkbox',
      labelEn: 'Which days will you attend?',
      labelZh: '您將參加哪幾天的活動？',
      descriptionEn: 'You may select multiple days.',
      descriptionZh: '您可以選擇多天。',
      required: true,
      options: [
        { value: 'day_1', labelEn: 'Day 1 (Opening)', labelZh: '第一天（開幕）' },
        { value: 'day_2_to_6', labelEn: 'Days 2-6 (Silent Practice)', labelZh: '第二天至第六天（止語實修）' },
        { value: 'day_7', labelEn: 'Day 7 (Closing)', labelZh: '第七天（閉幕）' }
      ]
    },
    {
      id: 'field_6',
      type: 'info',
      dataKey: 'medical_disclaimer',
      labelEn: 'Medical Disclaimer',
      labelZh: '醫療免責聲明',
      descriptionEn: 'By submitting this application, you confirm that you are physically and mentally capable of undertaking a rigorous meditation schedule.',
      descriptionZh: '提交此申請即表示您確認自己身心健康，能夠承擔嚴格的禪修日程。',
      required: false
    },
    {
      id: 'field_7',
      dataKey: 'id_upload',
      type: 'file',
      labelEn: 'Upload ID Document',
      labelZh: '上傳身份證明文件',
      descriptionEn: 'Please upload a scan of your ID card.',
      descriptionZh: '請上傳您的身份證掃描件。',
      required: false
    }
  ]
};

const dictionaries = {
  en: {
    back: 'Back to Event',
    officialForm: 'Official Application Form',
    selectDefault: 'Select an option...',
    submit: 'Submit Application',
    submitting: 'Submitting...',
    successTitle: 'Application Received!',
    successMessage: 'Thank you for applying. We have successfully received your application data.',
    nextSteps: 'We will review your application and contact you via email or WhatsApp within 3-5 working days.',
    returnToEvents: 'Return to Events',
    formClosed: 'Form Closed',
    closedSub: 'Applications for this retreat have reached capacity or the deadline has passed.',
    uploadFile: 'Click or drag file to upload',
    fileUploaded: 'File ready:'
  },
  zh: {
    back: '返回活動詳情',
    officialForm: '官方報名表單',
    selectDefault: '請選擇...',
    submit: '提交報名申請',
    submitting: '提交中...',
    successTitle: '報名申請已成功提交！',
    successMessage: '感謝您報名道跡禪院。我們已成功收到您的報名資料。',
    nextSteps: '我們將在 3-5 個工作日內審核您的申請，並透過電郵或 WhatsApp 與您聯繫。',
    returnToEvents: '返回活動列表',
    formClosed: '表單已關閉',
    closedSub: '此活動的報名名額已滿或已過截止日期。',
    uploadFile: '點擊或拖拽文件上傳',
    fileUploaded: '文件已準備好：'
  }
};

export default function ApplyPage({ params }: { params?: any }) {
  // Safely extract locale from Next 15 URL params
  const resolvedParams = params && typeof params.then === 'function' ? use(params) : params;
  const locale = (resolvedParams?.locale === 'zh' ? 'zh' : 'en') as 'en' | 'zh';
  
  const t = (key: keyof typeof dictionaries['en']) => dictionaries[locale][key];
  const formData = mockFormData;

  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [status, setStatus] = useState<'idle' | 'submitting' | 'success'>('idle');

  const handleInputChange = (key: string, value: string) => {
    setAnswers(prev => ({ ...prev, [key]: value }));
  };

  const handleCheckboxChange = (key: string, value: string, checked: boolean) => {
    setAnswers(prev => {
      // Store checkboxes as a comma-separated string for easy CSV parsing later
      const currentArr = prev[key] ? prev[key].split(',') : [];
      let newArr;
      if (checked) {
        newArr = [...currentArr, value];
      } else {
        newArr = currentArr.filter(v => v !== value);
      }
      return { ...prev, [key]: newArr.join(',') };
    });
  };

  const handleFileUpload = (key: string, e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // In reality: Trigger Supabase Storage upload, await URL, then save URL to state.
      // For now, mock it by saving the filename.
      setAnswers(prev => ({ ...prev, [key]: file.name }));
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('submitting');
    setTimeout(() => {
      setStatus('success');
      console.log("Submitted JSON Payload:", answers);
    }, 1200);
  };

  // Complex Logic Engine Evaluation
  const evaluateCondition = (condition: any) => {
    if (!condition || !condition.rules || condition.rules.length === 0) return true;
    
    const evaluateRule = (rule: any) => {
      const answer = answers[rule.dependsOn] || '';
      switch (rule.operator) {
        case 'equals': return answer === rule.value;
        case 'not_equals': return answer !== rule.value;
        case 'contains': return answer.toLowerCase().includes(rule.value.toLowerCase());
        case 'not_contains': return !answer.toLowerCase().includes(rule.value.toLowerCase());
        case 'is_blank': return answer.trim() === '';
        case 'is_not_blank': return answer.trim() !== '';
        default: return false;
      }
    };

    if (condition.match === 'OR') return condition.rules.some(evaluateRule);
    return condition.rules.every(evaluateRule); // AND
  };

  const visibleFields = formData.schema.filter(field => evaluateCondition(field.condition));

  return (
    <div className="w-full bg-[#FCFAF8] min-h-screen pb-32 font-sans text-stone-800">
      
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
        <a 
          href={`/${locale}/events/${formData.event_id}`} 
          className="inline-flex items-center text-sm font-medium text-stone-500 hover:text-[#A65D24] transition-colors group cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 mr-2 group-hover:-translate-x-1 transition-transform" />
          {t('back')}
        </a>
      </div>

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header Block */}
        <div className="bg-white rounded-3xl border border-stone-200 shadow-sm p-8 sm:p-10 mb-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
          <div className="inline-flex items-center px-3 py-1 rounded-md text-xs font-medium bg-[#FAF5F0] text-[#A65D24] mb-4">
            {t('officialForm')}
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-stone-800 tracking-tight mb-3 leading-snug">
            {locale === 'en' ? formData.titleEn : formData.titleZh}
          </h1>
          <MarkdownPreview 
            text={locale === 'en' ? formData.subtitleEn : formData.subtitleZh} 
            className="mb-5 text-base"
          />
          
          <div className="flex flex-col sm:flex-row gap-4 sm:gap-6 text-sm text-stone-500 font-medium pt-5 border-t border-stone-100">
            <div className="flex items-center">
              <Calendar className="w-4 h-4 mr-2 text-[#A65D24]" />
              {formData.schedule_display[locale]}
            </div>
            <div className="flex items-center">
              <MapPin className="w-4 h-4 mr-2 text-[#A65D24]" />
              {formData.location[locale]}
            </div>
          </div>
        </div>

        {formData.formStatus !== 'open' ? (
          <div className="bg-white rounded-3xl border border-stone-200 p-12 text-center shadow-sm">
            <div className="w-16 h-16 bg-stone-100 rounded-2xl flex items-center justify-center mx-auto mb-4 text-stone-400">
              <AlertCircle className="w-8 h-8" />
            </div>
            <h3 className="text-xl font-bold text-stone-800 mb-2">{t('formClosed')}</h3>
            <p className="text-stone-500 max-w-md mx-auto">{t('closedSub')}</p>
          </div>
        ) : status === 'success' ? (
          <div className="bg-white rounded-3xl border border-stone-200 p-8 sm:p-12 text-center shadow-sm animate-in fade-in zoom-in-95 duration-500">
            <div className="w-20 h-20 bg-emerald-50 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-6 border border-emerald-100">
              <CheckCircle2 className="w-10 h-10" />
            </div>
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-800 mb-4">{t('successTitle')}</h2>
            <p className="text-stone-600 text-base sm:text-lg mb-8 max-w-xl mx-auto leading-relaxed">
              {t('successMessage')}
            </p>
            <p className="text-stone-500 text-sm max-w-md mx-auto leading-relaxed mb-8">
              {t('nextSteps')}
            </p>
            <a 
              href={`/${locale}/events`}
              className="inline-flex items-center justify-center px-8 py-3.5 bg-[#A65D24] hover:bg-[#8B4D1E] text-white font-semibold rounded-xl transition-all shadow-sm cursor-pointer"
            >
              {t('returnToEvents')}
            </a>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="bg-white rounded-3xl border border-stone-200 shadow-sm p-8 sm:p-10 space-y-10 animate-in fade-in duration-500">
            
            <div className="space-y-8">
              {visibleFields.map((field: any) => (
                <div key={field.id} className="space-y-3 animate-in fade-in slide-in-from-bottom-2 duration-300">
                  
                  {field.type === 'info' ? (
                    <div className="bg-[#FAF5F0] p-6 rounded-2xl border border-[#F2E8DC]">
                      <h3 className="text-lg font-bold text-[#A65D24] mb-2">{locale === 'en' ? field.labelEn : field.labelZh}</h3>
                      <MarkdownPreview text={locale === 'en' ? field.descriptionEn : field.descriptionZh} className="!text-stone-600 !mt-0" />
                    </div>
                  ) : (
                    <>
                      <div>
                        <label className="block text-sm sm:text-base font-semibold text-stone-800">
                          {locale === 'en' ? field.labelEn : field.labelZh}
                          {field.required && <span className="text-[#A65D24] ml-1.5">*</span>}
                        </label>
                        <MarkdownPreview text={locale === 'en' ? field.descriptionEn : field.descriptionZh} />
                      </div>

                      {field.type === 'text' || field.type === 'email' ? (
                        <input 
                          type={field.type}
                          required={field.required}
                          value={answers[field.dataKey] || ''}
                          onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                          className="w-full px-4 py-3.5 rounded-xl border border-stone-200 focus:border-[#A65D24] focus:ring-2 focus:ring-[#A65D24]/20 outline-none transition-all text-stone-800 bg-stone-50/30"
                        />
                      ) : field.type === 'textarea' ? (
                        <textarea 
                          rows={4}
                          required={field.required}
                          value={answers[field.dataKey] || ''}
                          onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                          className="w-full px-4 py-3.5 rounded-xl border border-stone-200 focus:border-[#A65D24] focus:ring-2 focus:ring-[#A65D24]/20 outline-none transition-all text-stone-800 bg-stone-50/30 resize-y"
                        />
                      ) : field.type === 'mobile' ? (
                        <div className="relative">
                          <Smartphone className="absolute left-4 top-4 w-5 h-5 text-stone-400" />
                          <input 
                            type="tel"
                            required={field.required}
                            value={answers[field.dataKey] || ''}
                            onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                            placeholder="+852 1234 5678"
                            className="w-full pl-12 pr-4 py-3.5 rounded-xl border border-stone-200 focus:border-[#A65D24] focus:ring-2 focus:ring-[#A65D24]/20 outline-none transition-all text-stone-800 bg-stone-50/30"
                          />
                        </div>
                      ) : field.type === 'date' ? (
                        <div className="relative">
                          <Calendar className="absolute left-4 top-4 w-5 h-5 text-stone-400" />
                          <input 
                            type="date"
                            required={field.required}
                            value={answers[field.dataKey] || ''}
                            onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                            className="w-full pl-12 pr-4 py-3.5 rounded-xl border border-stone-200 focus:border-[#A65D24] focus:ring-2 focus:ring-[#A65D24]/20 outline-none transition-all text-stone-800 bg-stone-50/30"
                          />
                        </div>
                      ) : field.type === 'select' ? (
                        <div className="relative">
                          <select 
                            required={field.required}
                            value={answers[field.dataKey] || ''}
                            onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                            className="w-full px-4 py-3.5 rounded-xl border border-stone-200 focus:border-[#A65D24] focus:ring-2 focus:ring-[#A65D24]/20 outline-none transition-all text-stone-800 bg-white cursor-pointer appearance-none"
                          >
                            <option value="">{t('selectDefault')}</option>
                            {field.options?.map((opt: any, i: number) => (
                              <option key={i} value={opt.value}>{locale === 'en' ? opt.labelEn : opt.labelZh}</option>
                            ))}
                          </select>
                          <div className="pointer-events-none absolute inset-y-0 right-0 flex items-center px-4 text-stone-500">
                            <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7"></path></svg>
                          </div>
                        </div>
                      ) : field.type === 'radio' ? (
                        <div className="space-y-3 pt-1">
                          {field.options?.map((opt: any, i: number) => (
                            <label key={i} className="flex items-center p-3 sm:p-4 border border-stone-200 rounded-xl cursor-pointer hover:bg-[#FAF5F0] hover:border-[#A65D24] transition-colors group">
                              <input 
                                type="radio" 
                                name={field.dataKey}
                                required={field.required}
                                value={opt.value}
                                checked={answers[field.dataKey] === opt.value}
                                onChange={(e) => handleInputChange(field.dataKey, e.target.value)}
                                className="w-4 h-4 text-[#A65D24] border-stone-300 focus:ring-[#A65D24]"
                              />
                              <span className="ml-3 text-sm font-medium text-stone-700 group-hover:text-[#A65D24] transition-colors">
                                {locale === 'en' ? opt.labelEn : opt.labelZh}
                              </span>
                            </label>
                          ))}
                        </div>
                      ) : field.type === 'checkbox' ? (
                        <div className="space-y-3 pt-1">
                          {field.options?.map((opt: any, i: number) => {
                            const isChecked = (answers[field.dataKey] || '').split(',').includes(opt.value);
                            return (
                              <label key={i} className="flex items-center p-3 sm:p-4 border border-stone-200 rounded-xl cursor-pointer hover:bg-[#FAF5F0] hover:border-[#A65D24] transition-colors group">
                                <input 
                                  type="checkbox" 
                                  value={opt.value}
                                  checked={isChecked}
                                  onChange={(e) => handleCheckboxChange(field.dataKey, e.target.value, e.target.checked)}
                                  className="w-4 h-4 text-[#A65D24] border-stone-300 rounded focus:ring-[#A65D24]"
                                />
                                <span className="ml-3 text-sm font-medium text-stone-700 group-hover:text-[#A65D24] transition-colors">
                                  {locale === 'en' ? opt.labelEn : opt.labelZh}
                                </span>
                              </label>
                            );
                          })}
                        </div>
                      ) : field.type === 'file' ? (
                        <div className="relative">
                          <input 
                            type="file" 
                            id={`file-${field.id}`}
                            className="hidden" 
                            required={field.required && !answers[field.dataKey]}
                            onChange={(e) => handleFileUpload(field.dataKey, e)}
                          />
                          <label 
                            htmlFor={`file-${field.id}`}
                            className="border-2 border-dashed border-stone-300 rounded-xl p-8 flex flex-col items-center justify-center text-center bg-stone-50 hover:bg-[#FAF5F0] hover:border-[#A65D24] cursor-pointer transition-colors group"
                          >
                            {answers[field.dataKey] ? (
                              <>
                                <CheckCircle2 className="w-8 h-8 text-emerald-500 mb-3" />
                                <span className="text-sm font-medium text-stone-800">{t('fileUploaded')} {answers[field.dataKey]}</span>
                                <span className="text-xs text-stone-500 mt-1">Click to replace file</span>
                              </>
                            ) : (
                              <>
                                <UploadCloud className="w-8 h-8 text-stone-400 mb-3 group-hover:text-[#A65D24] transition-colors" />
                                <span className="text-sm font-medium text-stone-600 group-hover:text-[#A65D24] transition-colors">{t('uploadFile')}</span>
                                <span className="text-xs text-stone-400 mt-1">PDF, JPG, or PNG (Max 5MB)</span>
                              </>
                            )}
                          </label>
                        </div>
                      ) : null}
                    </>
                  )}
                </div>
              ))}
            </div>

            <div className="pt-8 mt-8 border-t border-stone-100">
              <button 
                type="submit"
                disabled={status === 'submitting'}
                className="w-full sm:w-auto px-8 py-4 bg-[#A65D24] hover:bg-[#8B4D1E] text-white text-lg font-semibold rounded-xl transition-all shadow-md hover:shadow-lg focus:ring-2 focus:ring-[#A65D24] focus:ring-offset-2 disabled:opacity-70 disabled:cursor-wait flex items-center justify-center mx-auto"
              >
                {status === 'submitting' ? (
                  <>
                    <Loader2 className="w-5 h-5 mr-3 animate-spin" />
                    {t('submitting')}
                  </>
                ) : (
                  t('submit')
                )}
              </button>
            </div>

          </form>
        )}

      </div>
    </div>
  );
}